### ISSUE TITLE
Generic type 'Observer<T>' requires 1 type argument(s)

### ISSUE THREAD

**Issue by ChristianGrieger** [javebratt/ionic-auth-email-firebase-sdk#1]
Hey,

i tried to add your login system to my project but its ending up with the following error:
```
[11:57:52]  typescript: node_modules/@firebase/auth-types/index.d.ts, line: 244
            Generic type 'Observer<T>' requires 1 type argument(s).
     L243:  signInAnonymously(): Promise<any>;
     L244:  signInAnonymouslyAndRetrieveData(): Promise<any>;
     L245:  signInWithCredential(credential: AuthCredential): Promise<any>;
[11:57:52]  typescript: node_modules/@firebase/auth-types/index.d.ts, line: 249
            Generic type 'Observer<T>' requires 1 type argument(s).
     L248:  signInWithEmailAndPassword(email: string, password: string): Promise<any>;
     L249:  signInAndRetrieveDataWithEmailAndPassword(
     L250:    email: string,
```
Image:
<img width="607" alt="error" src="https://user-images.githubusercontent.com/8712219/34822547-a8d617b2-f6c7-11e7-8308-aaaa5e61ea66.png">

When i close the error all seems to work well but when i refresh window or restart the app this happens all the time.

Do you have any idea how i can fix the problem?

Thanks.

Greetings,
Chris

**Comment by ChristianGrieger** [comment]
Updated to firebase 4.8.1 and now getting this errors:
<img width="717" alt="bildschirmfoto 2018-01-11 um 13 43 22" src="https://user-images.githubusercontent.com/8712219/34826082-727efc8e-f6d5-11e7-922b-1306f8058947.png">

**Comment by ChristianGrieger** [comment]
Changed now to firebase 4.7.0 and all works without errors but i think this should not be the solution :) ?

**Comment by javebratt** [comment]
Hey there,

Firebase 4.8.1 refactored its type declarations, when you update to 4.8.1 there is some refactoring you need to do. [I emailed my list about this a few weeks ago](https://ckarchive.com/b/wvu2hgh4k2wo).

**Comment by ChristianGrieger** [comment]
Okay you i right, i got that mail... sorry
But i really tried to import stuff seperated and did not have any success i will try it again. 

I was thinking when i follow this git and create all parts as you did i should be fine with 4.8.1 but as it looks like i am not as the first errors show.

**Comment by ChristianGrieger** [comment]
So i instealled 4.8.2 and it looks like it still works ;)

i only have two red lined words but app works without problems on login.ts

 const loginUser: **firebase**.User = await this.authProvider.loginUser(

and on signup.ts

const signupUser: **firebase**.User = await this.authProvider.signupUser(

that two firebase are underlined and it tells that the namespace is not there but the app works without errors?

**Comment by javebratt** [comment]
I'm going to be working on upgrading everything to 4.8.2, they fixed the type settings today

**Comment by ChristianGrieger** [comment]
Thank you very much :) i am also on 4.8.2 now.

**Comment by nayfin** [comment]
Can anyone post a link for changes required to use firebase 4.8.2 as well as required changes to utilize AngularFire2 please? I was able to find docs just after the change and now I can't find anything on it.
