### ISSUE TITLE
Request: mailchecker on validator

### ISSUE THREAD

**Issue by ChristianGrieger** [javebratt/ionic-auth-email-firebase-sdk#2]
Hey Jorge,

i dont know if you are open to add some little functions to the project but if so i would love to learn and see how you would add a mailchecker for the emails to the validator.

There is a nice project with a big object list that gets updated often and it would be nice to have a import option to the firebase database and a automated check on validation against the own database.

Trashmail check ;) from -> https://raw.githubusercontent.com/FGRibreau/mailchecker/c193518dab3c56833d999ccc6c409f44ec128724/list.json

Maybe you want to take a look on it with the next update and like the idea?

Greetings,
Chris

**Comment by javebratt** [comment]
Will look into it, good idea to filter my email list :+1:  :smiley:

**Comment by ChristianGrieger** [comment]
Nice! Thank you :)
