### ISSUE TITLE
Error on logout

### ISSUE THREAD

**Issue by tanjunior** [javebratt/ionic-auth-email-firebase-sdk#4]
code: "PERMISSION_DENIED"
columnNumber: 17
fileName: "http://localhost:8100/build/vendor.js"
lineNumber: 19355
message: "permission_denied at /user/FgiihmMj4tQ1bLLxzT5qijGdaeQ2: Client doesn't have permission to access the desired data.

**Comment by javebratt** [comment]
It's supposed to happen, when you log out you can't read the data protected by security rules 😃
